root@b1c304af3ba8://workspace/yolov9/yolov9-main# bash runGroupedTestsv9.sh 
Running val_dual on golf...
val_dual: data=data/grouped_test/golf/data.yaml, weights=['runs/train/yolov9-golf/weights/best.pt'], batch_size=32, imgsz=640, conf_thres=0.001, iou_thres=0.65, max_det=300, task=test, device=, workers=8, single_cls=False, augment=False, verbose=False, save_txt=False, save_hybrid=False, save_conf=False, save_json=False, project=runs/val, name=yolov9_test_golf, exist_ok=False, half=False, dnn=False, min_items=0
YOLO ðŸš€ 2025-5-6 Python-3.11.12 torch-2.7.0+cu126 CUDA:0 (NVIDIA GeForce RTX 3060 Laptop GPU, 6144MiB)

Fusing layers... 
yolov9-m summary: 588 layers, 32556058 parameters, 0 gradients, 130.7 GFLOPs
test: Scanning /workspace/yolov9/yolov9-main/data/grouped_test/golf/labels... 13 images, 0 backgrounds, 0 corrupt: 1
test: New cache created: /workspace/yolov9/yolov9-main/data/grouped_test/golf/labels.cache
                 Class     Images  Instances          P          R      mAP50   mAP50-95: 100%|â–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆ| 1/1 00:05
                   all         13         23      0.867      0.676      0.753      0.449
             club_head         13         11          1      0.769      0.952      0.644
              fmo_ball         13         12      0.734      0.583      0.554      0.254
Speed: 6.9ms pre-process, 252.3ms inference, 35.6ms NMS per image at shape (32, 3, 640, 640)
Exception in thread Thread-6 (plot_images):
Traceback (most recent call last):
  File "/opt/conda/lib/python3.11/threading.py", line 1045, in _bootstrap_inner
    self.run()
  File "/opt/conda/lib/python3.11/threading.py", line 982, in run
    self._target(*self._args, **self._kwargs)
  File "/workspace/yolov9/yolov9-main/utils/plots.py", line 300, in plot_images
Exception in thread Thread-7 (plot_images):
Traceback (most recent call last):
  File "/opt/conda/lib/python3.11/threading.py", line 1045, in _bootstrap_inner
    self.run()
      File "/opt/conda/lib/python3.11/threading.py", line 982, in run
annotator.box_label(box, label, color=color)
  File "/workspace/yolov9/yolov9-main/utils/plots.py", line 86, in box_label
    self._target(*self._args, **self._kwargs)
  File "/workspace/yolov9/yolov9-main/utils/plots.py", line 300, in plot_images
    w, h = self.font.getsize(label)  # text width, height
             annotator.box_label(box, label, color=color)
  ^^  File "/workspace/yolov9/yolov9-main/utils/plots.py", line 86, in box_label
^^^^^^^^^^^^^^^
AttributeError: 'FreeTypeFont' object has no attribute 'getsize'
    w, h = self.font.getsize(label)  # text width, height
           ^^^^^^^^^^^^^^^^^
AttributeError: 'FreeTypeFont' object has no attribute 'getsize'
Results saved to runs/val/yolov9_test_golf4
Running val_dual on golf10...
val_dual: data=data/grouped_test/golf10/data.yaml, weights=['runs/train/yolov9-golf/weights/best.pt'], batch_size=32, imgsz=640, conf_thres=0.001, iou_thres=0.65, max_det=300, task=test, device=, workers=8, single_cls=False, augment=False, verbose=False, save_txt=False, save_hybrid=False, save_conf=False, save_json=False, project=runs/val, name=yolov9_test_golf10, exist_ok=False, half=False, dnn=False, min_items=0
YOLO ðŸš€ 2025-5-6 Python-3.11.12 torch-2.7.0+cu126 CUDA:0 (NVIDIA GeForce RTX 3060 Laptop GPU, 6144MiB)

Fusing layers...
yolov9-m summary: 588 layers, 32556058 parameters, 0 gradients, 130.7 GFLOPs
test: Scanning /workspace/yolov9/yolov9-main/data/grouped_test/golf10/labels... 3 images, 0 backgrounds, 0 corrupt:
test: New cache created: /workspace/yolov9/yolov9-main/data/grouped_test/golf10/labels.cache
                 Class     Images  Instances          P          R      mAP50   mAP50-95: 100%|â–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆ| 1/1 00:01
                   all          3          5      0.966          1      0.995      0.495
             club_head          3          2      0.951          1      0.995      0.648
              fmo_ball          3          3       0.98          1      0.995      0.343
Speed: 1.6ms pre-process, 243.7ms inference, 140.6ms NMS per image at shape (32, 3, 640, 640)
Exception in thread Thread-6 (plot_images):
Traceback (most recent call last):
  File "/opt/conda/lib/python3.11/threading.py", line 1045, in _bootstrap_inner
Exception in thread Thread-7 (plot_images):
Traceback (most recent call last):
  File "/opt/conda/lib/python3.11/threading.py", line 1045, in _bootstrap_inner
    self.run()
  File "/opt/conda/lib/python3.11/threading.py", line 982, in run
    self.run()
  File "/opt/conda/lib/python3.11/threading.py", line 982, in run
    self._target(*self._args, **self._kwargs)
  File "/workspace/yolov9/yolov9-main/utils/plots.py", line 300, in plot_images
    self._target(*self._args, **self._kwargs)
  File "/workspace/yolov9/yolov9-main/utils/plots.py", line 300, in plot_images
    annotator.box_label(box, label, color=color)
annotator.box_label(box, label, color=color)  File "/workspace/yolov9/yolov9-main/utils/plots.py", line 86, in box_label

  File "/workspace/yolov9/yolov9-main/utils/plots.py", line 86, in box_label
    w, h = self.font.getsize(label)  # text width, height    w, h = self.font.getsize(label)  # text width, height

                     ^^^ ^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'FreeTypeFont' object has no attribute 'getsize'
^^^^^^^^^^
AttributeError: 'FreeTypeFont' object has no attribute 'getsize'
Results saved to runs/val/yolov9_test_golf104
Running val_dual on golf11...
val_dual: data=data/grouped_test/golf11/data.yaml, weights=['runs/train/yolov9-golf/weights/best.pt'], batch_size=32, imgsz=640, conf_thres=0.001, iou_thres=0.65, max_det=300, task=test, device=, workers=8, single_cls=False, augment=False, verbose=False, save_txt=False, save_hybrid=False, save_conf=False, save_json=False, project=runs/val, name=yolov9_test_golf11, exist_ok=False, half=False, dnn=False, min_items=0
YOLO ðŸš€ 2025-5-6 Python-3.11.12 torch-2.7.0+cu126 CUDA:0 (NVIDIA GeForce RTX 3060 Laptop GPU, 6144MiB)

Fusing layers... 
yolov9-m summary: 588 layers, 32556058 parameters, 0 gradients, 130.7 GFLOPs
test: Scanning /workspace/yolov9/yolov9-main/data/grouped_test/golf11/labels... 2 images, 0 backgrounds, 0 corrupt: 100%|â–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆ| 2/2 00:00
test: New cache created: /workspace/yolov9/yolov9-main/data/grouped_test/golf11/labels.cache
                 Class     Images  Instances          P          R      mAP50   mAP50-95: 100%|â–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆ| 1/1 00:01
                   all          2          4      0.904      0.986      0.995      0.492
             club_head          2          2      0.808          1      0.995      0.571
              fmo_ball          2          2          1      0.973      0.995      0.414
Speed: 1.9ms pre-process, 293.8ms inference, 182.4ms NMS per image at shape (32, 3, 640, 640)
Exception in thread Thread-6 (plot_images):
Traceback (most recent call last):
  File "/opt/conda/lib/python3.11/threading.py", line 1045, in _bootstrap_inner
    Exception in thread Thread-7 (plot_images):
Traceback (most recent call last):
self.run()
  File "/opt/conda/lib/python3.11/threading.py", line 982, in run
  File "/opt/conda/lib/python3.11/threading.py", line 1045, in _bootstrap_inner
    self.run()
  File "/opt/conda/lib/python3.11/threading.py", line 982, in run
    self._target(*self._args, **self._kwargs)
  File "/workspace/yolov9/yolov9-main/utils/plots.py", line 300, in plot_images
    self._target(*self._args, **self._kwargs)    
annotator.box_label(box, label, color=color)
  File "/workspace/yolov9/yolov9-main/utils/plots.py", line 86, in box_label
  File "/workspace/yolov9/yolov9-main/utils/plots.py", line 300, in plot_images
    annotator.box_label(box, label, color=color)    w, h = self.font.getsize(label)  # text width, height

     File "/workspace/yolov9/yolov9-main/utils/plots.py", line 86, in box_label
        ^^    ^^w, h = self.font.getsize(label)  # text width, height^
^^    ^    ^   ^^^^^^^^^^^^^^
^AttributeError^: ^'FreeTypeFont' object has no attribute 'getsize'^^^
^^^^^
AttributeError: 'FreeTypeFont' object has no attribute 'getsize'
Results saved to runs/val/yolov9_test_golf113
Running val_dual on golf12...
val_dual: data=data/grouped_test/golf12/data.yaml, weights=['runs/train/yolov9-golf/weights/best.pt'], batch_size=32, imgsz=640, conf_thres=0.001, iou_thres=0.65, max_det=300, task=test, device=, workers=8, single_cls=False, augment=False, verbose=False, save_txt=False, save_hybrid=False, save_conf=False, save_json=False, project=runs/val, name=yolov9_test_golf12, exist_ok=False, half=False, dnn=False, min_items=0
YOLO ðŸš€ 2025-5-6 Python-3.11.12 torch-2.7.0+cu126 CUDA:0 (NVIDIA GeForce RTX 3060 Laptop GPU, 6144MiB)

Fusing layers... 
yolov9-m summary: 588 layers, 32556058 parameters, 0 gradients, 130.7 GFLOPs
test: Scanning /workspace/yolov9/yolov9-main/data/grouped_test/golf12/labels... 1 images, 0 backgrounds, 0 corrupt: 100%|â–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆ| 1/1 00:00
test: New cache created: /workspace/yolov9/yolov9-main/data/grouped_test/golf12/labels.cache
                 Class     Images  Instances          P          R      mAP50   mAP50-95: 100%|â–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆ| 1/1 00:01
Exception in thread Thread-5 (plot_images)                   all          1          1          1          1      0.995      0.697
              fmo_ball          1          1          1          1      0.995      0.697
Speed: 1.8ms pre-process, 395.5ms inference, 325.3ms NMS per image at shape (32, 3, 640, 640)
:
Exception in thread Thread-6 (plot_images):
Traceback (most recent call last):
  File "/opt/conda/lib/python3.11/threading.py", line 1045, in _bootstrap_inner
Traceback (most recent call last):
  File "/opt/conda/lib/python3.11/threading.py", line 1045, in _bootstrap_inner
    self.run()
  File "/opt/conda/lib/python3.11/threading.py", line 982, in run
    self.run()
  File "/opt/conda/lib/python3.11/threading.py", line 982, in run
    self._target(*self._args, **self._kwargs)
  File "/workspace/yolov9/yolov9-main/utils/plots.py", line 300, in plot_images
    self._target(*self._args, **self._kwargs)
  File "/workspace/yolov9/yolov9-main/utils/plots.py", line 300, in plot_images
    annotator.box_label(box, label, color=color)
      File "/workspace/yolov9/yolov9-main/utils/plots.py", line 86, in box_label
annotator.box_label(box, label, color=color)
  File "/workspace/yolov9/yolov9-main/utils/plots.py", line 86, in box_label
    w, h = self.font.getsize(label)  # text width, height
           ^^^^^^^^^^^^^^^^^
AttributeError: 'FreeTypeFont' object has no attribute 'getsize'
    w, h = self.font.getsize(label)  # text width, height
           ^^^^^^^^^^^^^^^^^
AttributeError: 'FreeTypeFont' object has no attribute 'getsize'
Results saved to runs/val/yolov9_test_golf12
Running val_dual on golf13...
val_dual: data=data/grouped_test/golf13/data.yaml, weights=['runs/train/yolov9-golf/weights/best.pt'], batch_size=32, imgsz=640, conf_thres=0.001, iou_thres=0.65, max_det=300, task=test, device=, workers=8, single_cls=False, augment=False, verbose=False, save_txt=False, save_hybrid=False, save_conf=False, save_json=False, project=runs/val, name=yolov9_test_golf13, exist_ok=False, half=False, dnn=False, min_items=0
YOLO ðŸš€ 2025-5-6 Python-3.11.12 torch-2.7.0+cu126 CUDA:0 (NVIDIA GeForce RTX 3060 Laptop GPU, 6144MiB)

Fusing layers... 
yolov9-m summary: 588 layers, 32556058 parameters, 0 gradients, 130.7 GFLOPs
test: Scanning /workspace/yolov9/yolov9-main/data/grouped_test/golf13/labels... 8 images, 0 backgrounds, 0 corrupt: 100%|â–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆ| 8/8 00:00
test: New cache created: /workspace/yolov9/yolov9-main/data/grouped_test/golf13/labels.cache
                 Class     Images  Instances          P          R      mAP50   mAP50-95: 100%|â–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆ| 1/1 00:03
                   all          8         12      0.802      0.917      0.898      0.406
             club_head          8          6      0.608      0.833      0.802       0.44
              fmo_ball          8          6      0.997          1      0.995      0.371
Speed: 5.1ms pre-process, 245.0ms inference, 40.3ms NMS per image at shape (32, 3, 640, 640)
Exception in thread Thread-6 (plot_images):
Traceback (most recent call last):
  File "/opt/conda/lib/python3.11/threading.py", line 1045, in _bootstrap_inner
Exception in thread Thread-7 (plot_images)    self.run():

  File "/opt/conda/lib/python3.11/threading.py", line 982, in run
Traceback (most recent call last):
  File "/opt/conda/lib/python3.11/threading.py", line 1045, in _bootstrap_inner
    self._target(*self._args, **self._kwargs)
      File "/workspace/yolov9/yolov9-main/utils/plots.py", line 300, in plot_images
self.run()
  File "/opt/conda/lib/python3.11/threading.py", line 982, in run
    self._target(*self._args, **self._kwargs)
  File "/workspace/yolov9/yolov9-main/utils/plots.py", line 300, in plot_images
    annotator.box_label(box, label, color=color)    annotator.box_label(box, label, color=color)
  File "/workspace/yolov9/yolov9-main/utils/plots.py", line 86, in box_label

  File "/workspace/yolov9/yolov9-main/utils/plots.py", line 86, in box_label
    w, h = self.font.getsize(label)  # text width, height
           ^^^^^^^^^^^^^^^^^
AttributeError    w, h = self.font.getsize(label)  # text width, height:
'FreeTypeFont' object has no attribute 'getsize'
          ^^^^^^^^^^^^^^^^^
AttributeError: 'FreeTypeFont' object has no attribute 'getsize'
Results saved to runs/val/yolov9_test_golf13
Running val_dual on golf18...
val_dual: data=data/grouped_test/golf18/data.yaml, weights=['runs/train/yolov9-golf/weights/best.pt'], batch_size=32, imgsz=640, conf_thres=0.001, iou_thres=0.65, max_det=300, task=test, device=, workers=8, single_cls=False, augment=False, verbose=False, save_txt=False, save_hybrid=False, save_conf=False, save_json=False, project=runs/val, name=yolov9_test_golf18, exist_ok=False, half=False, dnn=False, min_items=0
YOLO ðŸš€ 2025-5-6 Python-3.11.12 torch-2.7.0+cu126 CUDA:0 (NVIDIA GeForce RTX 3060 Laptop GPU, 6144MiB)

Fusing layers... 
yolov9-m summary: 588 layers, 32556058 parameters, 0 gradients, 130.7 GFLOPs
test: Scanning /workspace/yolov9/yolov9-main/data/grouped_test/golf18/labels... 2 images, 0 backgrounds, 0 corrupt: 100%|â–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆ| 2/2 00:00
test: New cache created: /workspace/yolov9/yolov9-main/data/grouped_test/golf18/labels.cache
                 Class     Images  Instances          P          R      mAP50   mAP50-95: 100%|â–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆ| 1/1 00:00
                   all          2          4      0.952        0.5       0.72      0.388
                  ball          2          2      0.967        0.5      0.745      0.521
             club_head          2          2      0.938        0.5      0.695      0.254
Exception in thread Speed: 0.6ms pre-process, 76.5ms inference, 67.5ms NMS per image at shape (32, 3, 640, 640)
Exception in thread Thread-6 (plot_images)Thread-7 (plot_images):
Traceback (most recent call last):
:
Traceback (most recent call last):
  File "/opt/conda/lib/python3.11/threading.py", line 1045, in _bootstrap_inner
  File "/opt/conda/lib/python3.11/threading.py", line 1045, in _bootstrap_inner
    self.run()
  File "/opt/conda/lib/python3.11/threading.py", line 982, in run
    self.run()    self._target(*self._args, **self._kwargs)

  File "/workspace/yolov9/yolov9-main/utils/plots.py", line 300, in plot_images
  File "/opt/conda/lib/python3.11/threading.py", line 982, in run
    self._target(*self._args, **self._kwargs)
  File "/workspace/yolov9/yolov9-main/utils/plots.py", line 300, in plot_images
    annotator.box_label(box, label, color=color)
  File "/workspace/yolov9/yolov9-main/utils/plots.py", line 86, in box_label
    annotator.box_label(box, label, color=color)
  File "/workspace/yolov9/yolov9-main/utils/plots.py", line 86, in box_label
    w, h = self.font.getsize(label)  # text width, height
      w, h = self.font.getsize(label)  # text width, height
              ^ ^^ ^  ^  ^^^^^^^^^^^^^^^^^
^AttributeError: ^^^^'FreeTypeFont' object has no attribute 'getsize'
^^^^^^^
AttributeError: 'FreeTypeFont' object has no attribute 'getsize'
Results saved to runs/val/yolov9_test_golf18
Running val_dual on golf19...
val_dual: data=data/grouped_test/golf19/data.yaml, weights=['runs/train/yolov9-golf/weights/best.pt'], batch_size=32, imgsz=640, conf_thres=0.001, iou_thres=0.65, max_det=300, task=test, device=, workers=8, single_cls=False, augment=False, verbose=False, save_txt=False, save_hybrid=False, save_conf=False, save_json=False, project=runs/val, name=yolov9_test_golf19, exist_ok=False, half=False, dnn=False, min_items=0
YOLO ðŸš€ 2025-5-6 Python-3.11.12 torch-2.7.0+cu126 CUDA:0 (NVIDIA GeForce RTX 3060 Laptop GPU, 6144MiB)

Fusing layers... 
yolov9-m summary: 588 layers, 32556058 parameters, 0 gradients, 130.7 GFLOPs
test: Scanning /workspace/yolov9/yolov9-main/data/grouped_test/golf19/labels... 7 images, 0 backgrounds, 0 corrupt: 100%|â–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆ| 7/7 00:00
test: New cache created: /workspace/yolov9/yolov9-main/data/grouped_test/golf19/labels.cache
                 Class     Images  Instances          P          R      mAP50   mAP50-95: 100%|â–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆ| 1/1 00:01
                   all          7         10      0.482      0.583      0.609      0.372
                  ball          7          3      0.697      0.667      0.702      0.492
             club_head          7          4      0.433       0.75      0.757      0.403
              fmo_ball          7          3      0.317      0.333      0.368      0.221
Speed: 3.3ms pre-process, 63.1ms inference, 24.3ms NMS per image at shape (32, 3, 640, 640)
Exception in thread Thread-6 (plot_images):
Traceback (most recent call last):
Exception in thread   File "/opt/conda/lib/python3.11/threading.py", line 1045, in _bootstrap_inner
Thread-7 (plot_images):
Traceback (most recent call last):
      File "/opt/conda/lib/python3.11/threading.py", line 1045, in _bootstrap_inner
self.run()
  File "/opt/conda/lib/python3.11/threading.py", line 982, in run
        self.run()
self._target(*self._args, **self._kwargs)  File "/opt/conda/lib/python3.11/threading.py", line 982, in run

  File "/workspace/yolov9/yolov9-main/utils/plots.py", line 300, in plot_images
    self._target(*self._args, **self._kwargs)
  File "/workspace/yolov9/yolov9-main/utils/plots.py", line 300, in plot_images
    annotator.box_label(box, label, color=color)
  File "/workspace/yolov9/yolov9-main/utils/plots.py", line 86, in box_label
    annotator.box_label(box, label, color=color)
  File "/workspace/yolov9/yolov9-main/utils/plots.py", line 86, in box_label
    w, h = self.font.getsize(label)  # text width, height
      w, h = self.font.getsize(label)  # text width, height
              ^^ ^  ^ ^ ^^^^^^^^^^^^^^^^^^^^^^^^^
^AttributeError^: ^^'FreeTypeFont' object has no attribute 'getsize'

AttributeError: 'FreeTypeFont' object has no attribute 'getsize'
Results saved to runs/val/yolov9_test_golf19
Running val_dual on golf4...
val_dual: data=data/grouped_test/golf4/data.yaml, weights=['runs/train/yolov9-golf/weights/best.pt'], batch_size=32, imgsz=640, conf_thres=0.001, iou_thres=0.65, max_det=300, task=test, device=, workers=8, single_cls=False, augment=False, verbose=False, save_txt=False, save_hybrid=False, save_conf=False, save_json=False, project=runs/val, name=yolov9_test_golf4, exist_ok=False, half=False, dnn=False, min_items=0
YOLO ðŸš€ 2025-5-6 Python-3.11.12 torch-2.7.0+cu126 CUDA:0 (NVIDIA GeForce RTX 3060 Laptop GPU, 6144MiB)

Fusing layers... 
yolov9-m summary: 588 layers, 32556058 parameters, 0 gradients, 130.7 GFLOPs
test: Scanning /workspace/yolov9/yolov9-main/data/grouped_test/golf4/labels... 4 images, 0 backgrounds, 0 corrupt: 100%|â–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆ| 4/4 00:00
test: New cache created: /workspace/yolov9/yolov9-main/data/grouped_test/golf4/labels.cache
                 Class     Images  Instances          P          R      mAP50   mAP50-95: 100%|â–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆ| 1/1 00:00
                   all          4          7      0.611      0.542      0.521      0.327
             club_head          4          4      0.741       0.75      0.856      0.526
Exception in thread               fmo_ball          4          3      0.481      0.333      0.185      0.129
Thread-6 (plot_images)Speed: 0.5ms pre-process, 54.6ms inference, 36.6ms NMS per image at shape (32, 3, 640, 640)
:
Exception in thread Traceback (most recent call last):
  File "/opt/conda/lib/python3.11/threading.py", line 1045, in _bootstrap_inner
Thread-7 (plot_images):
Traceback (most recent call last):
  File "/opt/conda/lib/python3.11/threading.py", line 1045, in _bootstrap_inner
    self.run()    
self.run()
  File "/opt/conda/lib/python3.11/threading.py", line 982, in run
  File "/opt/conda/lib/python3.11/threading.py", line 982, in run
        self._target(*self._args, **self._kwargs)self._target(*self._args, **self._kwargs)

  File "/workspace/yolov9/yolov9-main/utils/plots.py", line 300, in plot_images
  File "/workspace/yolov9/yolov9-main/utils/plots.py", line 300, in plot_images
    annotator.box_label(box, label, color=color)
  File "/workspace/yolov9/yolov9-main/utils/plots.py", line 86, in box_label
    annotator.box_label(box, label, color=color)
  File "/workspace/yolov9/yolov9-main/utils/plots.py", line 86, in box_label
    w, h = self.font.getsize(label)  # text width, height
           ^^^^^^    w, h = self.font.getsize(label)  # text width, height
^ ^^^^^^ ^  ^ ^^
 AttributeError  :  'FreeTypeFont' object has no attribute 'getsize'
  ^^^^^^^^^^^^^^^^^
AttributeError: 'FreeTypeFont' object has no attribute 'getsize'
Results saved to runs/val/yolov9_test_golf42
Running val_dual on golf5...
val_dual: data=data/grouped_test/golf5/data.yaml, weights=['runs/train/yolov9-golf/weights/best.pt'], batch_size=32, imgsz=640, conf_thres=0.001, iou_thres=0.65, max_det=300, task=test, device=, workers=8, single_cls=False, augment=False, verbose=False, save_txt=False, save_hybrid=False, save_conf=False, save_json=False, project=runs/val, name=yolov9_test_golf5, exist_ok=False, half=False, dnn=False, min_items=0
YOLO ðŸš€ 2025-5-6 Python-3.11.12 torch-2.7.0+cu126 CUDA:0 (NVIDIA GeForce RTX 3060 Laptop GPU, 6144MiB)

Fusing layers... 
yolov9-m summary: 588 layers, 32556058 parameters, 0 gradients, 130.7 GFLOPs
test: Scanning /workspace/yolov9/yolov9-main/data/grouped_test/golf5/labels... 2 images, 0 backgrounds, 0 corrupt: 100%|â–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆ| 2/2 00:00
test: New cache created: /workspace/yolov9/yolov9-main/data/grouped_test/golf5/labels.cache
                 Class     Images  Instances          P          R      mAP50   mAP50-95: 100%|â–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆ| 1/1 00:00
Exception in thread Thread-6 (plot_images):
Traceback (most recent call last):
                   all          2          2      0.793          1      0.995      0.597
             club_head          2          1      0.668          1      0.995      0.497
  File "/opt/conda/lib/python3.11/threading.py", line 1045, in _bootstrap_inner
              fmo_ball          2          1      0.918          1      0.995      0.697
Exception in thread Thread-7 (plot_images)Speed: 0.8ms pre-process, 70.7ms inference, 79.1ms NMS per image at shape (32, 3, 640, 640)
:
Traceback (most recent call last):
    self.run()
  File "/opt/conda/lib/python3.11/threading.py", line 982, in run
  File "/opt/conda/lib/python3.11/threading.py", line 1045, in _bootstrap_inner
    self.run()
  File "/opt/conda/lib/python3.11/threading.py", line 982, in run
    self._target(*self._args, **self._kwargs)
  File "/workspace/yolov9/yolov9-main/utils/plots.py", line 300, in plot_images
    self._target(*self._args, **self._kwargs)
  File "/workspace/yolov9/yolov9-main/utils/plots.py", line 300, in plot_images
    annotator.box_label(box, label, color=color)    annotator.box_label(box, label, color=color)

  File "/workspace/yolov9/yolov9-main/utils/plots.py", line 86, in box_label
  File "/workspace/yolov9/yolov9-main/utils/plots.py", line 86, in box_label
    w, h = self.font.getsize(label)  # text width, height
    w, h = self.font.getsize(label)  # text width, height
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
^AttributeError: ^
'FreeTypeFont' object has no attribute 'getsize'AttributeError
: 'FreeTypeFont' object has no attribute 'getsize'
Results saved to runs/val/yolov9_test_golf5
Running val_dual on golf6...
val_dual: data=data/grouped_test/golf6/data.yaml, weights=['runs/train/yolov9-golf/weights/best.pt'], batch_size=32, imgsz=640, conf_thres=0.001, iou_thres=0.65, max_det=300, task=test, device=, workers=8, single_cls=False, augment=False, verbose=False, save_txt=False, save_hybrid=False, save_conf=False, save_json=False, project=runs/val, name=yolov9_test_golf6, exist_ok=False, half=False, dnn=False, min_items=0
YOLO ðŸš€ 2025-5-6 Python-3.11.12 torch-2.7.0+cu126 CUDA:0 (NVIDIA GeForce RTX 3060 Laptop GPU, 6144MiB)

Fusing layers... 
yolov9-m summary: 588 layers, 32556058 parameters, 0 gradients, 130.7 GFLOPs
test: Scanning /workspace/yolov9/yolov9-main/data/grouped_test/golf6/labels... 16 images, 0 backgrounds, 0 corrupt: 100%|â–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆ| 16/16 00:00
test: New cache created: /workspace/yolov9/yolov9-main/data/grouped_test/golf6/labels.cache
                 Class     Images  Instances          P          R      mAP50   mAP50-95: 100%|â–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆ| 1/1 00:01
                   all         16         27      0.937      0.825      0.942       0.63
                  ball         16          1      0.951          1      0.995      0.796
             club_head         16         16          1      0.863      0.965      0.655
              fmo_ball         16         10      0.859      0.612      0.868      0.438
Speed: 3.1ms pre-process, 57.7ms inference, 8.4ms NMS per image at shape (32, 3, 640, 640)
Exception in thread Thread-6 (plot_images):
Traceback (most recent call last):
  File "/opt/conda/lib/python3.11/threading.py", line 1045, in _bootstrap_inner
    self.run()
  File "/opt/conda/lib/python3.11/threading.py", line 982, in run
    self._target(*self._args, **self._kwargs)
  File "/workspace/yolov9/yolov9-main/utils/plots.py", line 300, in plot_images
    annotator.box_label(box, label, color=color)
  File "/workspace/yolov9/yolov9-main/utils/plots.py", line 86, in box_label
    w, h = self.font.getsize(label)  # text width, height
           ^^^^^^^^^^^^^^^^^
AttributeError: 'FreeTypeFont' object has no attribute 'getsize'
Exception in thread Thread-7 (plot_images):
Traceback (most recent call last):
  File "/opt/conda/lib/python3.11/threading.py", line 1045, in _bootstrap_inner
    self.run()
  File "/opt/conda/lib/python3.11/threading.py", line 982, in run
    self._target(*self._args, **self._kwargs)
  File "/workspace/yolov9/yolov9-main/utils/plots.py", line 300, in plot_images
    annotator.box_label(box, label, color=color)
  File "/workspace/yolov9/yolov9-main/utils/plots.py", line 86, in box_label
    w, h = self.font.getsize(label)  # text width, height
           ^^^^^^^^^^^^^^^^^
AttributeError: 'FreeTypeFont' object has no attribute 'getsize'
Results saved to runs/val/yolov9_test_golf6
Running val_dual on golf7...
val_dual: data=data/grouped_test/golf7/data.yaml, weights=['runs/train/yolov9-golf/weights/best.pt'], batch_size=32, imgsz=640, conf_thres=0.001, iou_thres=0.65, max_det=300, task=test, device=, workers=8, single_cls=False, augment=False, verbose=False, save_txt=False, save_hybrid=False, save_conf=False, save_json=False, project=runs/val, name=yolov9_test_golf7, exist_ok=False, half=False, dnn=False, min_items=0
YOLO ðŸš€ 2025-5-6 Python-3.11.12 torch-2.7.0+cu126 CUDA:0 (NVIDIA GeForce RTX 3060 Laptop GPU, 6144MiB)

Fusing layers... 
yolov9-m summary: 588 layers, 32556058 parameters, 0 gradients, 130.7 GFLOPs
test: Scanning /workspace/yolov9/yolov9-main/data/grouped_test/golf7/labels... 1 images, 0 backgrounds, 0 corrupt: 100%|â–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆ| 1/1 00:00
test: New cache created: /workspace/yolov9/yolov9-main/data/grouped_test/golf7/labels.cache
                 Class     Images  Instances          P          R      mAP50   mAP50-95: 100%|â–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆ| 1/1 00:00
Exception in thread                    all          1          2       0.25        0.5      0.497     0.0995
Thread-5 (plot_images)             club_head          1          1          0          0          0          0
:
Traceback (most recent call last):
  File "/opt/conda/lib/python3.11/threading.py", line 1045, in _bootstrap_inner
              fmo_ball          1          1        0.5          1      0.995      0.199
Speed: 0.8ms pre-process, 113.4ms inference, 162.5ms NMS per image at shape (32, 3, 640, 640)
    self.run()
  File "/opt/conda/lib/python3.11/threading.py", line 982, in run
    self._target(*self._args, **self._kwargs)
  File "/workspace/yolov9/yolov9-main/utils/plots.py", line 300, in plot_images
    annotator.box_label(box, label, color=color)
  File "/workspace/yolov9/yolov9-main/utils/plots.py", line 86, in box_label
    w, h = self.font.getsize(label)  # text width, height
           ^^^^^^^^^^^^^^^^^
AttributeError: 'FreeTypeFont' object has no attribute 'getsize'
Results saved to runs/val/yolov9_test_golf7
Running val_dual on golf8...
val_dual: data=data/grouped_test/golf8/data.yaml, weights=['runs/train/yolov9-golf/weights/best.pt'], batch_size=32, imgsz=640, conf_thres=0.001, iou_thres=0.65, max_det=300, task=test, device=, workers=8, single_cls=False, augment=False, verbose=False, save_txt=False, save_hybrid=False, save_conf=False, save_json=False, project=runs/val, name=yolov9_test_golf8, exist_ok=False, half=False, dnn=False, min_items=0
YOLO ðŸš€ 2025-5-6 Python-3.11.12 torch-2.7.0+cu126 CUDA:0 (NVIDIA GeForce RTX 3060 Laptop GPU, 6144MiB)

Fusing layers... 
yolov9-m summary: 588 layers, 32556058 parameters, 0 gradients, 130.7 GFLOPs
test: Scanning /workspace/yolov9/yolov9-main/data/grouped_test/golf8/labels... 28 images, 0 backgrounds, 0 corrupt: 100%|â–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆ| 28/28 00:00
test: New cache created: /workspace/yolov9/yolov9-main/data/grouped_test/golf8/labels.cache
                 Class     Images  Instances          P          R      mAP50   mAP50-95: 100%|â–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆ| 1/1 00:02
                   all         28         35      0.803      0.909      0.831       0.49
                  ball         28          2      0.632          1      0.663      0.424
             club_head         28         12      0.906      0.917      0.972      0.615
              fmo_ball         28         21      0.871       0.81      0.857      0.433
Speed: 2.2ms pre-process, 40.8ms inference, 9.1ms NMS per image at shape (32, 3, 640, 640)
Exception in thread Thread-6 (plot_images):
Traceback (most recent call last):
  File "/opt/conda/lib/python3.11/threading.py", line 1045, in _bootstrap_inner
    self.run()
  File "/opt/conda/lib/python3.11/threading.py", line 982, in run
    self._target(*self._args, **self._kwargs)
  File "/workspace/yolov9/yolov9-main/utils/plots.py", line 300, in plot_images
    annotator.box_label(box, label, color=color)
  File "/workspace/yolov9/yolov9-main/utils/plots.py", line 86, in box_label
    w, h = self.font.getsize(label)  # text width, height
           ^^^^^^^^^^^^^^^^^
AttributeError: 'FreeTypeFont' object has no attribute 'getsize'
Exception in thread Thread-7 (plot_images):
Traceback (most recent call last):
  File "/opt/conda/lib/python3.11/threading.py", line 1045, in _bootstrap_inner
    self.run()
  File "/opt/conda/lib/python3.11/threading.py", line 982, in run
    self._target(*self._args, **self._kwargs)
  File "/workspace/yolov9/yolov9-main/utils/plots.py", line 300, in plot_images
    annotator.box_label(box, label, color=color)
  File "/workspace/yolov9/yolov9-main/utils/plots.py", line 86, in box_label
    w, h = self.font.getsize(label)  # text width, height
           ^^^^^^^^^^^^^^^^^
AttributeError: 'FreeTypeFont' object has no attribute 'getsize'
Results saved to runs/val/yolov9_test_golf8
Running val_dual on golf9...
val_dual: data=data/grouped_test/golf9/data.yaml, weights=['runs/train/yolov9-golf/weights/best.pt'], batch_size=32, imgsz=640, conf_thres=0.001, iou_thres=0.65, max_det=300, task=test, device=, workers=8, single_cls=False, augment=False, verbose=False, save_txt=False, save_hybrid=False, save_conf=False, save_json=False, project=runs/val, name=yolov9_test_golf9, exist_ok=False, half=False, dnn=False, min_items=0
YOLO ðŸš€ 2025-5-6 Python-3.11.12 torch-2.7.0+cu126 CUDA:0 (NVIDIA GeForce RTX 3060 Laptop GPU, 6144MiB)

Fusing layers... 
yolov9-m summary: 588 layers, 32556058 parameters, 0 gradients, 130.7 GFLOPs
test: Scanning /workspace/yolov9/yolov9-main/data/grouped_test/golf9/labels... 4 images, 0 backgrounds, 0 corrupt: 100%|â–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆ| 4/4 00:00
test: New cache created: /workspace/yolov9/yolov9-main/data/grouped_test/golf9/labels.cache
                 Class     Images  Instances          P          R      mAP50   mAP50-95: 100%|â–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆ| 1/1 00:00
Exception in thread Thread-6 (plot_images):
                   all          4          8      0.882      0.884      0.953      0.576
                  ball          4          1      0.724          1      0.995      0.497
Traceback (most recent call last):
  File "/opt/conda/lib/python3.11/threading.py", line 1045, in _bootstrap_inner
             club_head          4          4      0.922       0.75       0.87      0.617
              fmo_ball          4          3          1      0.901      0.995      0.612
Speed: 0.5ms pre-process, 72.2ms inference, 48.6ms NMS per image at shape (32, 3, 640, 640)
    self.run()
  File "/opt/conda/lib/python3.11/threading.py", line 982, in run
Exception in thread Thread-7 (plot_images):
    Traceback (most recent call last):
self._target(*self._args, **self._kwargs)  File "/opt/conda/lib/python3.11/threading.py", line 1045, in _bootstrap_inner

  File "/workspace/yolov9/yolov9-main/utils/plots.py", line 300, in plot_images
    self.run()
  File "/opt/conda/lib/python3.11/threading.py", line 982, in run
    self._target(*self._args, **self._kwargs)
  File "/workspace/yolov9/yolov9-main/utils/plots.py", line 300, in plot_images
    annotator.box_label(box, label, color=color)
  File "/workspace/yolov9/yolov9-main/utils/plots.py", line 86, in box_label
    w, h = self.font.getsize(label)  # text width, height    
annotator.box_label(box, label, color=color)
     File "/workspace/yolov9/yolov9-main/utils/plots.py", line 86, in box_label
        ^^^^^^^^^^^^    ^^^^w, h = self.font.getsize(label)  # text width, height
 ^
 AttributeError: 'FreeTypeFont' object has no attribute 'getsize'
        ^^^^^^^^^^^^^^^^^
AttributeError: 'FreeTypeFont' object has no attribute 'getsize'
Results saved to runs/val/yolov9_test_golf9
Running val_dual on yt_misc...
val_dual: data=data/grouped_test/yt_misc/data.yaml, weights=['runs/train/yolov9-golf/weights/best.pt'], batch_size=32, imgsz=640, conf_thres=0.001, iou_thres=0.65, max_det=300, task=test, device=, workers=8, single_cls=False, augment=False, verbose=False, save_txt=False, save_hybrid=False, save_conf=False, save_json=False, project=runs/val, name=yolov9_test_yt_misc, exist_ok=False, half=False, dnn=False, min_items=0
YOLO ðŸš€ 2025-5-6 Python-3.11.12 torch-2.7.0+cu126 CUDA:0 (NVIDIA GeForce RTX 3060 Laptop GPU, 6144MiB)

Fusing layers... 
yolov9-m summary: 588 layers, 32556058 parameters, 0 gradients, 130.7 GFLOPs
test: Scanning /workspace/yolov9/yolov9-main/data/grouped_test/yt_misc/labels... 19 images, 0 backgrounds, 0 corrupt: 100%|â–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆ| 19/19 00:00
test: New cache created: /workspace/yolov9/yolov9-main/data/grouped_test/yt_misc/labels.cache
                 Class     Images  Instances          P          R      mAP50   mAP50-95: 100%|â–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆ| 1/1 00:01
                   all         19         35      0.637      0.643      0.647      0.394
                  ball         19         12      0.915      0.903      0.983      0.612
             club_head         19         19      0.814      0.842      0.891      0.522
              fmo_ball         19          4      0.183      0.183     0.0669     0.0468
Speed: 3.5ms pre-process, 40.7ms inference, 9.7ms NMS per image at shape (32, 3, 640, 640)
Exception in thread Thread-6 (plot_images):
Traceback (most recent call last):
  File "/opt/conda/lib/python3.11/threading.py", line 1045, in _bootstrap_inner
    self.run()
  File "/opt/conda/lib/python3.11/threading.py", line 982, in run
    self._target(*self._args, **self._kwargs)
  File "/workspace/yolov9/yolov9-main/utils/plots.py", line 300, in plot_images
    annotator.box_label(box, label, color=color)
  File "/workspace/yolov9/yolov9-main/utils/plots.py", line 86, in box_label
    w, h = self.font.getsize(label)  # text width, height
           ^^^^^^^^^^^^^^^^^
AttributeError: 'FreeTypeFont' object has no attribute 'getsize'
Exception in thread Thread-7 (plot_images):
Traceback (most recent call last):
  File "/opt/conda/lib/python3.11/threading.py", line 1045, in _bootstrap_inner
    self.run()
  File "/opt/conda/lib/python3.11/threading.py", line 982, in run
    self._target(*self._args, **self._kwargs)
  File "/workspace/yolov9/yolov9-main/utils/plots.py", line 300, in plot_images
    annotator.box_label(box, label, color=color)
  File "/workspace/yolov9/yolov9-main/utils/plots.py", line 86, in box_label
    w, h = self.font.getsize(label)  # text width, height
           ^^^^^^^^^^^^^^^^^
AttributeError: 'FreeTypeFont' object has no attribute 'getsize'
Results saved to runs/val/yolov9_test_yt_misc
root@b1c304af3ba8://workspace/yolov9/yolov9-main# 